# Generated by Django 4.2.3 on 2023-07-11 09:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_model', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='')),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('dogovor', models.BooleanField()),
                ('email', models.EmailField(max_length=254)),
                ('characteristics', models.TextField()),
                ('memory', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_model', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('dogovor', models.BooleanField()),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=100)),
                ('characteristics', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_model', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='')),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('dogovor', models.BooleanField()),
                ('email', models.EmailField(max_length=254)),
                ('characteristics', models.TextField()),
                ('memory', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Telev',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_model', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='')),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('dogovor', models.BooleanField()),
                ('email', models.EmailField(max_length=254)),
                ('characteristics', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('firm', models.CharField(max_length=100)),
                ('model_product', models.CharField(max_length=100)),
                ('ikpu_product', models.CharField(max_length=100)),
                ('color_product', models.CharField(max_length=100)),
                ('country_manufacture', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('laptop', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='takes.laptop')),
                ('phone', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='takes.phone')),
                ('plan', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='takes.plan')),
                ('telev', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='takes.telev')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
